### ISSUE TITLE
The plugin `epub_viewer` uses a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by Shivere** [JideGuru/epub_viewer#109]
**Crash / Error**

The plugin `epub_viewer` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this
plugin supports the Android V2 embedding. Otherwise, consider removing it since a
future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2
embedding: https://flutter.dev/go/android-plugin-migration.

**Steps to reproduce:**

`flutter pub get`

_Flutter version 2.5.0_

**Comment by mghase** [comment]
any solution

**Comment by JideGuru** [comment]
please Try version 0.2.3
