### ISSUE TITLE
Support for epub v3. 

### ISSUE THREAD

**Issue by lateef4web** [JideGuru/epub_viewer#11]
I observed that the epub reader doesnot open epub v3( Like alice in wonderland). Everything is blank and the app crash atimes. Please help.

**Comment by JideGuru** [comment]
Thanks for reporting this.
Did you stumble upon this on Android or iOS? And where there any crash logs?

**Comment by lateef4web** [comment]
Sorry for the late response. On Android platform.

**Comment by JideGuru** [comment]
when you say it does not support epub v3, what do you mean? can you share a screenshot or an error log?

**Comment by nishantjoshee** [comment]
> I observed that the epub reader doesnot open epub v3( Like alice in wonderland). Everything is blank and the app crash atimes. Please help.

could you please show me your code that runs successfully for epub v2? I am getting trouble for using this plugin.

**Comment by JideGuru** [comment]
@nishantjoshee if you're getting an error then you should open an issue ticket explain the error that you got!

**Comment by JideGuru** [comment]
Conversations on this issue will be continued in #43
