### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method open on channel epub_viewer)

### ISSUE THREAD

**Issue by nkenna** [JideGuru/epub_viewer#110]
Issue / Feature -  Unhandled Exception: MissingPluginException(No implementation found for method open on channel epub_viewer)
Platform (android, iOS or both) - android
Crash / Error - E/flutter ( 9795): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method open on channel epub_viewer)

**Comment by siloebb** [comment]
I downloaded the example today and happens with me too.

**Comment by JideGuru** [comment]
Which Flutter version did tis error occur on please?

**Comment by nkenna** [comment]
Flutter 2.2.2

**Comment by nkenna** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.2, on Linux, locale en_NG)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)

**Comment by JideGuru** [comment]
Did you try flutter clean?

**Comment by siloebb** [comment]
[✓] Flutter (Channel stable, 2.5.0, on Mac OS X 10.15.6 19G73 darwin-x64, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.60.1)
[✓] Connected device (2 available)

• No issues found!

**Comment by nkenna** [comment]
done that. closed android studio and tried again. Still getting the same error

**Comment by JideGuru** [comment]
One last question. What version of the plugin are you using? Have you tried 0.2.3?

**Comment by nkenna** [comment]
Yes. the lastest version

**Comment by JideGuru** [comment]
I just deployed a fix (version 0.2.4). Please try it and let me know how it goes.
