### ISSUE TITLE
Reading file from assets.

### ISSUE THREAD

**Issue by nishantjoshee** [JideGuru/epub_viewer#19]
How do I read and show epub file from assets? 
Like: assets/myfile.epub in my project. Could you show a sample code just for that? I don't need other features such as download. I just need to read file from my project's asset folder.

**Comment by JideGuru** [comment]
As shown in this repo's readme, you can read from your assets using `EpubViewer.openAsset()` like this

```
await EpubViewer.openAsset(
  'assets/3.epub',
  lastLocation: EpubLocator.fromJson({
      "bookId": "2239",
      "href": "/OEBPS/ch06.xhtml",
      "created": 1539934158390,
      "locations": {
         "cfi": "epubcfi(/0!/4/4[simple_book]/2/2/6)"
      }
  }), // first page will open up if the value is null
 );
```

replace the `assets/3.epub` with your asset's path

**Comment by nishantjoshee** [comment]
Thank you so much.
