### ISSUE TITLE
app crashing in relase mode

### ISSUE THREAD

**Issue by dineshpote26** [JideGuru/epub_viewer#23]
App Crashing in release mode showing the following error

n.a.a.e: Subscriber class com.folioreader.q.c.b and its super classes have no public methods with the @Subscribe annotation

any idea what is this?

**Comment by JideGuru** [comment]
Hi, Thanks for reporting this issue.
I'll look into it and fix it as soon as I'm available

**Comment by dineshpote26** [comment]
@JideGuru Any update or workaround on this?

**Comment by JideGuru** [comment]
@dineshpote26 i'm still working on it. I'll release a new version of the plugin soon. I've been a bit busy

**Comment by kapiltandukar** [comment]
@dineshpote26 is it working on your ios?

**Comment by JideGuru** [comment]
@dineshpote26 
add this to the release build type in your app build.gradle

```
minifyEnable false
shrinkResources false
```
<img width="496" alt="Screenshot 2020-10-13 at 17 17 29" src="https://user-images.githubusercontent.com/24323581/95887620-fa819e00-0d77-11eb-8ebb-f6482b808d6b.png">

**Comment by kehindeegunjobi93** [comment]
> @dineshpote26
> add this to the release build type in your app build.gradle
> 
> ```
> minifyEnable false
> shrinkResources false
> ```
> 
> <img alt="Screenshot 2020-10-13 at 17 17 29" width="496" src="https://user-images.githubusercontent.com/24323581/95887620-fa819e00-0d77-11eb-8ebb-f6482b808d6b.png">

Hello chief. I get an error when I add those lines into it. It says
<img width="266" alt="Capture2" src="https://user-images.githubusercontent.com/16244953/96385905-d74b5a00-118e-11eb-9637-192dd5fbe041.PNG">


Could not find method minifyEnable() for arguments [false] on BuildType_Decorated

**Comment by JideGuru** [comment]
I made a typo its `minifyEnabled` not `minifyEnable`

**Comment by JideGuru** [comment]
@dineshpote26 is this issue fixed for you?

**Comment by dineshpote26** [comment]
@JideGuru Fixed the issue after adding the following prograd rules.

-keepattributes *Annotation*
-keepclassmembers class ** {
    @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }
# Only required if you usenter code heree AsyncExecutor
-keepclassmembers class * extends org.greenrobot.eventbus.util.ThrowableFailureEvent {
    <init>(java.lang.Throwable);
}

**Comment by kehindeegunjobi93** [comment]
> @kehindeegunjobi93 I made a typo its `minifyEnabled` not `minifyEnable`

Thanks, it worked
