### ISSUE TITLE
FolioReaderKit for IOS uses UIWebView which has been deprecated

### ISSUE THREAD

**Issue by shivamkejriwal9** [JideGuru/epub_viewer#25]
**Issue**  - epub_viewer uses FolioReaderKit for IOS which uses UIWebView which has been deprecated
**Platform** - IOS
**Error** - The app is not being accepted to the app store during review

![Issue Image](https://user-images.githubusercontent.com/58459382/93873920-29b06c80-fcf0-11ea-91b4-b67c43915545.jpeg)

**Comment by JideGuru** [comment]
Ohh wow.
I'll keep this issue at high priority and get back to you as soon as possible.

**Comment by JideGuru** [comment]
Hello @shivamkejriwal9 
I just published version 0.1.9 which fixes this problem
