### ISSUE TITLE
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\epub_viewer-0.1.7\android\src\main\java\com\jideguru\epub_viewer\EpubViewerPlugin.java uses unchecked or unsafe operations. Note: Recompile with -Xlint:unchecked for details.

### ISSUE THREAD

**Issue by Sahmirzali** [JideGuru/epub_viewer#26]
Issue / Feature - 
Platform  - Anroid 
Crash / Error -  Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\epub_viewer-0.1.7\android\src\main\java\com\jideguru\epub_viewer\EpubViewerPlugin.java uses unchecked or unsafe operations. Note: Recompile with -Xlint:unchecked for details.

**_i running project in release mode.  these is writing in console. can you solve this issue ?_** 

Running Gradle task 'assembleRelease'...                                
**Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\epub_viewer-0.1.7\android\src\main\java\com\jideguru\epub_viewer\EpubViewerPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.**
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                     548.6s (!)
√ Built build\app\outputs\flutter-apk\app-release.apk (14.4MB).
Installing build\app\outputs\flutter-apk\app.apk...                 4.7s

Flutter run key commands.
h Repeat this help message.
c Clear the screen
q Quit (terminate the application on the device).
**I/flutterEbookAp(11876): Reinit property: dalvik.vm.checkjni= false
E/flutterEbookAp(11876): Not starting debugger since process cannot load the jdwp agent.
I/flutterEbookAp(11876): QarthPatchMonintor::Init
I/flutterEbookAp(11876): 
I/flutterEbookAp(11876): QarthPatchMonintor::StartWatch
I/flutterEbookAp(11876):
I/flutterEbookAp(11876): QarthPatchMonintor::WatchPackage: /data/hotpatch/fwkhotpatch/
I/flutterEbookAp(11876):
I/flutterEbookAp(11876): QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/dev.jideguru.flutterEbookApp
I/flutterEbookAp(11876):
I/flutterEbookAp(11876): QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/all
I/flutterEbookAp(11876):
I/flutterEbookAp(11876): QarthPatchMonintor::Run
I/flutterEbookAp(11876):
I/flutterEbookAp(11876): QarthPatchMonintor::Reading
I/flutterEbookAp(11876):
I/flutterEbookAp(11876): QarthPatchMonintor::CheckNotifyEvent
I/flutterEbookAp(11876):
I/flutterEbookAp(11876): QarthPatchMonintor::CheckNotifyEvent before read
I/flutterEbookAp(11876):**

**Comment by JideGuru** [comment]
That's a warning not an error so you're safe. Does it stop the project from running or working?

**Comment by Sahmirzali** [comment]
No doesn't stop. But i see now this epub package doesn't have horizontal view.  only have vertical. but epub kitty have both .
can you add also horizontal view please ?

**Comment by JideGuru** [comment]
There's is horizontal view. EpubDirection.horizontal

**Comment by Sahmirzali** [comment]
how can i make  both of them ? at the same time( optional ) vertical , horizontal

**Comment by Sahmirzali** [comment]
Thanks. I have one question more. How can i open epub from asset ? in this example exist from api

**Comment by Sahmirzali** [comment]
can i add there my own fonts ?

**Comment by JideGuru** [comment]
It's in the readme of the repo. Please reference it. Thanks

**Comment by JideGuru** [comment]
No you cannot add your own font at the moment
