### ISSUE TITLE
language

### ISSUE THREAD

**Issue by Sahmirzali** [JideGuru/epub_viewer#27]
**Hello. How can i change epub reader language(english)  to other language? 
for example words :  copy, share, vertical, horizontal ?**

   **_i find these in ios file but android don't have? please help :)_** 

/* 
  Localizable.strings
  Runner

  Created by 小发工作室 on 2019/11/16.
  Copyright © 2019 The Chromium Authors. All rights reserved.
*/
"Highlight" = "高亮";
"Define" = "查询";
"Note" = "笔记";

"Day" = "白天";
"Night" = "夜晚";
"Horizontal" = "左右翻页";
"Vertical" = "上下翻页";
"minutes" = "分钟";
"1 minute" = "1 分钟";
"Less than a minute" = "少于1分钟";
"minutes" = "分钟";
"1 page left" = "剩余1页";
"pages left" = "剩余页数";

"Share" = "分享";
"Cancel" = "取消";
"Save" = "保存";
"Done" = "完成";
"Manage" = "管理";
"Search Web" = "网页查找";

"Contents" = "目录";
"Highlights" = "笔记";

**Comment by JideGuru** [comment]
Use `res/values/strings.xml` to match this 

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="FolioReader">FolioReader</string>
    <string name="direction_vertical">Verticale</string>
    <string name="direction_horizontal">Horizontale</string>
    <string name="contents">Contenu</string>
    <string name="highlights">Points forts</string>
    <string name="copy">Copie</string>
    <string name="share">Partager</string>
    <string name="define">Définir</string>
    <string name="highlight">surligner</string>
</resources>
```

**Comment by 312654929** [comment]
> **Hello. How can i change epub reader language(english) to other language? for example words : copy, share, vertical, horizontal ?**
> 
> **_i find these in ios file but android don't have? please help :)_**
> 
> /*
> Localizable.strings
> Runner
> 
> Created by 小发工作室 on 2019/11/16.
> Copyright © 2019 The Chromium Authors. All rights reserved.
> */
> "Highlight" = "高亮";
> "Define" = "查询";
> "Note" = "笔记";
> 
> "Day" = "白天";
> "Night" = "夜晚";
> "Horizontal" = "左右翻页";
> "Vertical" = "上下翻页";
> "minutes" = "分钟";
> "1 minute" = "1 分钟";
> "Less than a minute" = "少于1分钟";
> "minutes" = "分钟";
> "1 page left" = "剩余1页";
> "pages left" = "剩余页数";
> 
> "Share" = "分享";
> "Cancel" = "取消";
> "Save" = "保存";
> "Done" = "完成";
> "Manage" = "管理";
> "Search Web" = "网页查找";
> 
> "Contents" = "目录";
> "Highlights" = "笔记";

您好您解决了吗，我没有找到strings.xml文件。
