### ISSUE TITLE
Blank screen is shown when epub_viewer initiates.

### ISSUE THREAD

**Issue by pratham-xp** [JideGuru/epub_viewer#30]
Issue / Feature - Blank screen is shown when epub_viewer initiates. 
Platform (android, iOS or both) -
Crash / Error - The app crashes when the drawer is clicked.

Steps to reproduce / Describe in detail - 
<img width="1371" alt="Screenshot 2020-09-30 at 12 35 04 AM" src="https://user-images.githubusercontent.com/59138245/94604198-f1db9300-02b4-11eb-8fd2-094bff767a72.png">

**Comment by JideGuru** [comment]
what's the value of `bookData.items[i].path`? Is it an asset path?

can you paste the error in your console?

**Comment by pratham-xp** [comment]
Yes.
path: assets/eBooks/Subtle Art.epub

**Comment by JideGuru** [comment]
Please use EpubViewer.openAsset() to view assets not EpubViewer.open()

**Comment by JideGuru** [comment]
@pratham-xp does that fix the problem for you?

**Comment by pratham-xp** [comment]
Yeah! Thank you.
