### ISSUE TITLE
horizontal scrolling doesnt work for ios

### ISSUE THREAD

**Issue by mrifni** [JideGuru/epub_viewer#37]
with this config

EpubViewer.setConfig(
          themeColor: Theme.of(context).accentColor,
          identifier: "iosBook",
          scrollDirection: EpubScrollDirection.HORIZONTAL,
          allowSharing: true,
          enableTts: true,
        );

**Comment by kapiltandukar** [comment]
@mrifni is it working on your ios ?

**Comment by mrifni** [comment]
its not working on IOS, i mentioned that in the issue title

**Comment by JideGuru** [comment]
Please update to version 0.1.9

**Comment by kanybekov66** [comment]
It still doesn't work on iOS

> Please update to version 0.1.9

**Comment by 312654929** [comment]
> Please update to version 0.1.9

It still doesn't work on iOS

**Comment by JuniorFlorentino** [comment]
Horizontal Scrolling Not Working on iOS versão  0.2.4
