### ISSUE TITLE
Unable to determine Swift version on iOS

### ISSUE THREAD

**Issue by luis-cruzt** [JideGuru/epub_viewer#4]
I'm getting the following error when doing pod install:

```
[!] Unable to determine Swift version for the following pods:

- `RealmSwift` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
- `epub_kitty` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

**Comment by JideGuru** [comment]
What version of the plugin are you using?

**Comment by luis-cruzt** [comment]
I'm using the latest version.

`epub_viewer: ^0.0.7`

**Comment by JideGuru** [comment]
Are you using swift with your project? the ios section.

**Comment by JideGuru** [comment]
This happens to most Flutter plugins. 
Follow this comment to fix this issue
https://github.com/esysberlin/esys-flutter-share/issues/24#issuecomment-527611976

**Comment by luis-cruzt** [comment]
So to run this plugin swift is required, right?

**Comment by JideGuru** [comment]
Yes. swift is required

**Comment by luis-cruzt** [comment]
The readme should contain that swift is required to run this plugin and also set the minimum deployment target to 10.0

**Comment by JideGuru** [comment]
You're right and the minimum deployment target is 9.0.
Thanks for pointing that out

**Comment by JideGuru** [comment]
I'll be closing this issue now
