### ISSUE TITLE
Highlighting removal is not working

### ISSUE THREAD

**Issue by alexanderpehlivanov** [JideGuru/epub_viewer#44]
Issue / Feature -
Platform (android, iOS or both) -
Crash / Error - 

Steps to reproduce / Describe in detail -

**Comment by JideGuru** [comment]
Care to explain with screenshots what this issue means?

**Comment by alexanderpehlivanov** [comment]
![Screenshot_1602847822](https://user-images.githubusercontent.com/14877055/96253899-13c75c00-0fbd-11eb-8df2-fb183f3af00a.jpg)

Hi mate,

Thank you for your fast response and sorry for not explaining the problem well enough.

What I mean is that when you highlight the text you can not unhighlight it.

**Comment by alexanderpehlivanov** [comment]
Mate sorry for taking your time it is working properly my bad.
