### ISSUE TITLE
App crashing on physical device, working fine on emulator

### ISSUE THREAD

**Issue by jishant07** [JideGuru/epub_viewer#48]
Issue / Feature - Opening Assets and Network Epubs
Platform (android, iOS or both) -
Crash / Error - The app runs perfectly on the emulator but the same apk crashes when installed on a real device.

Steps to reproduce / Describe in detail - I just installed the plugin and wrote the code as directed. 

Can you help me in a direction that can help me solve this issue? Any help will be appreciated.

**Comment by JideGuru** [comment]
does this fix your issue?
https://github.com/JideGuru/epub_viewer/issues/23#issuecomment-707854528

**Comment by jishant07** [comment]
Hey, I tried it still crashes. The plugin is so good. I really don't want to shift to something else and I think there isn't anything that has this many features. 

Any help will be appreciated.
