### ISSUE TITLE
Load epub from assets

### ISSUE THREAD

**Issue by luis-cruzt** [JideGuru/epub_viewer#5]
This plugin allows loading epub files from the Flutter assets folder?

I'm getting a book not found error.

**Comment by JideGuru** [comment]
No support for assets yet. I'm actively working on that

**Comment by JideGuru** [comment]
@luis-cruzt I've included a load from asset feature from `0.1.7`. You can now load EPUBs from your assets folder

**Comment by luis-cruzt** [comment]
Wow thanks, I'll take a look to that! Thank you
