### ISSUE TITLE
Bookmark 

### ISSUE THREAD

**Issue by syedecryptr** [JideGuru/epub_viewer#50]
Issue / Feature - Feature
Platform (android, iOS or both) - Android preferably

Steps to reproduce / Describe in detail - 

Bookmark feature is not available in folioreader, can this be achieved here? One way I was thinking to store the last location on some button press, is this possible, any insight would be helpful.

**Comment by JideGuru** [comment]
@syedecryptr Nice idea you have there but I'm already looking into migrating the plugin to Readium

**Comment by dymxin** [comment]
How soon? And what are the advantages?

**Comment by dymxin** [comment]
> @syedecryptr Nice idea you have there but I'm already looking into migrating the plugin to Readium

How soon? And what are the advantages?

**Comment by JideGuru** [comment]
Soon could be anytime between 2weeks to 1 month.
the advantages are mainly that Readium is actively maintained, unlike Folioreader which makes things easier. Readium also has this Bookmark feature.

**Comment by dymxin** [comment]
> Soon could be anytime between 2weeks to 1 month.
> 
> the advantages are mainly that Readium is actively maintained, unlike Folioreader which makes things easier. Readium also has this Bookmark feature.

I just took a look at Readium, it looks awesome! It has TTS too. Please can you do 2weeks!!!? Lolz

**Comment by syedecryptr** [comment]
> @syedecryptr Nice idea you have there but I'm already looking into migrating the plugin to Readium

Thanks for the awesome work. 

There is also one open-source ebook android project actively maintained https://github.com/foobnix/LibreraReader
quite overwhelming for me to be honest.

**Comment by mrifni** [comment]
which Readium repo ?
Ive heared its not maintained at all.

**Comment by JideGuru** [comment]
@mrifni You might've heard wrong. check out the organization and repositories here https://github.com/readium

**Comment by mrifni** [comment]
oh nice cheers man.

**Comment by syedecryptr** [comment]
Bookmark feature added in the repo :

https://github.com/syedecryptr/Folioreader-Bookmark
