### ISSUE TITLE
Example app doesn't print current location

### ISSUE THREAD

**Issue by jorpyl** [JideGuru/epub_viewer#53]
Issue / Feature -Issue
Platform (android, iOS or both) -android
Crash / Error - error

Steps to reproduce / Describe in detail -
In this  [example](https://github.com/JideGuru/epub_viewer/tree/master/example) app print function in there doesn't print anything
`EpubViewer.locatorStream.listen((locator) {`
                      `print(`
                          `'LOCATOR: ${EpubLocator.fromJson(jsonDecode(locator))}');`
                    `});`

**Comment by bkoznov** [comment]
@jorpyl  did you fix this? I am having a similar problem.

**Comment by bkoznov** [comment]
It looks like in the example app, the `onListen` is never being triggered. 

   ```    
     public void onListen(Object o, EventChannel.EventSink eventSink) {
                pageEventSink = eventSink;
            }
```

And therefore, when 

```
  if (pageEventSink != null){
            pageEventSink.success(read_locator.toJson());
        }
``` happens, no success event is emitted. Still unsure how this is occurring though...

**Comment by ameteku** [comment]
@JideGuru Just created a pr for this issue:
https://github.com/JideGuru/epub_viewer/compare/master...ameteku:master
