### ISSUE TITLE
Show Total page count and No of Pages left

### ISSUE THREAD

**Issue by kuntadynithesh** [JideGuru/epub_viewer#6]
Is there any chance you can add this feature ? .  Folio reader lacks this . This will be handy !

**Comment by JideGuru** [comment]
This is available. check the screenshot i attached
![IMG_4878](https://user-images.githubusercontent.com/24323581/92476971-b549d980-f1d7-11ea-8076-8b40911cac49.PNG)

**Comment by kuntadynithesh** [comment]
I am not able to figure out how . Can you please let me know how to implement it or property to be set ?

**Comment by JideGuru** [comment]
It's only available on iOS for now. If you run your app on iOS it should display out of the box. Make sure you're using the latest plugin version

**Comment by kuntadynithesh** [comment]
Is there any chance that you will make it work on android version too ?

**Comment by JideGuru** [comment]
Yes I'll work on it soon

**Comment by kuntadynithesh** [comment]
Thanks will appreciate that

**Comment by JideGuru** [comment]
@kuntadynithesh  i published a new version(0.1.4) that shows the page indicator on android but it doesn't seem to show on all devices. I'll be working on fixing that and I'll get back to you when all is fixed
![screenshot-1599848596697](https://user-images.githubusercontent.com/24323581/92961849-e4767a00-f467-11ea-8203-d972a6833456.jpg)

**Comment by JideGuru** [comment]
@kuntadynithesh Finally perfected the features in `0.1.6`. Update the plugin to the latest version and you'll get the feature!

**Comment by kuntadynithesh** [comment]
Awesome . Thanks mate !
