### ISSUE TITLE
set Scroll Direction as both vertical and horizontal

### ISSUE THREAD

**Issue by MrUnfunny** [JideGuru/epub_viewer#7]
Hi @JideGuru, currently EpubScrollDirection only has options to set scroll direction as either vertical or Horizontal. I'm not getting the option to switch between the two inside folioReader. Can you please guide me on how to implement this switching feature?

![WhatsApp Image 2020-09-08 at 7 03 58 PM](https://user-images.githubusercontent.com/43833743/92483311-4fc11180-f206-11ea-8c84-37c94083af55.jpeg)

**Comment by JideGuru** [comment]
Hey, @MrUnfunny  I can implement this in for you in about an hour as I'm still actively working on the plugin.
Thanks

**Comment by MrUnfunny** [comment]
@JideGuru That's very cool. I'll be waiting.

**Comment by JideGuru** [comment]
I pushed another version that included `EpubScrollDirection.ALLDIRECTIONS`

```
EpubViewer.setConfig(
    themeColor: Theme.of(context).primaryColor,
     identifier: "iosBook",
     scrollDirection: EpubScrollDirection.ALLDIRECTIONS,
     allowSharing: true,
     enableTts: true,
);
```

**Comment by MrUnfunny** [comment]
This works perfectly fine, Thanks
