### ISSUE TITLE
Ios Features doesn't work

### ISSUE THREAD

**Issue by felixferr** [JideGuru/epub_viewer#74]
Issue / Feature - takes notes, highlight, dark mode and zoom
Platform (android, iOS or both) - IOS
Crash / Error - 

Steps to reproduce / Describe in detail - 

The functionality on IOS doesn't works like takes notes, highlight , dark mode and zoom. On android it's works fine.

**Comment by kumbhdesign** [comment]
hello ios Feature issue how to resolve
because i face same issue in ios not work mode change,font size change
