### ISSUE TITLE
EpubViewer.open don't working

### ISSUE THREAD

**Issue by Aksoyhlc** [JideGuru/epub_viewer#78]
### **The file path does not work when entered, cannot find the file.**

path: /data/user/0/com.app.name/app_flutter/books/24.epub

`EpubViewer.open(
       path,
      lastLocation: EpubLocator.fromJson({
        "bookId": "324234",
        "href": "/OEBPS/ch06.xhtml",
        "created": 1539934158390,
        "locations": {"cfi": "epubcfi(/0!/4/4[simple_book]/2/2/6)"}
      }),
    );`

### **_The following codes are working_**

EpubViewer.openAsset(
     "assets/24.epub",
      lastLocation: EpubLocator.fromJson({
        "bookId": "324234",
        "href": "/OEBPS/ch06.xhtml",
        "created": 1539934158390,
        "locations": {"cfi": "epubcfi(/0!/4/4[simple_book]/2/2/6)"}
      }),
    );

**Comment by JideGuru** [comment]
Is the file saved on your device?

**Comment by Aksoyhlc** [comment]
> Is the file saved on your device?

Evet kayıt edildi dosya yolu doğru.

**Comment by Aksoyhlc** [comment]
@JideGuru Is there any improvement? I need this feature very much.

**Comment by JideGuru** [comment]
@Aksoyhlc I think you should investigate your file path

**Comment by Aksoyhlc** [comment]
V/FolioActivity(22696): -> setDayMode
V/FolioActivity(22696): -> initMediaController
V/FolioActivity(22696): -> setupBook
V/FolioActivity(22696): -> initBook
**### E/Error   (22696): Could not generate container**
**### E/Error   (22696): java.util.zip.ZipException: error in opening zip file**
E/Error   (22696): 	at java.util.zip.ZipFile.open(Native Method)
E/Error   (22696): 	at java.util.zip.ZipFile.<init>(ZipFile.java:265)
E/Error   (22696): 	at java.util.zip.ZipFile.<init>(ZipFile.java:187)
E/Error   (22696): 	at java.util.zip.ZipFile.<init>(ZipFile.java:158)
E/Error   (22696): 	at org.readium.r2.streamer.container.ContainerEpub.<init>(ContainerEpub.kt:56)
E/Error   (22696): 	at org.readium.r2.streamer.parser.EpubParser.generateContainerFrom(EpubParser.kt:55)
E/Error   (22696): 	at org.readium.r2.streamer.parser.EpubParser.parse(EpubParser.kt:71)
E/Error   (22696): 	at com.folioreader.ui.activity.FolioActivity.initBook(FolioActivity.kt:517)
E/Error   (22696): 	at com.folioreader.ui.activity.FolioActivity.setupBook(FolioActivity.kt:487)
E/Error   (22696): 	at com.folioreader.ui.activity.FolioActivity.onCreate(FolioActivity.kt:301)
E/Error   (22696): 	at android.app.Activity.performCreate(Activity.java:7893)
E/Error   (22696): 	at android.app.Activity.performCreate(Activity.java:7880)
E/Error   (22696): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
E/Error   (22696): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3310)
E/Error   (22696): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3484)
E/Error   (22696): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/Error   (22696): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/Error   (22696): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/Error   (22696): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
E/Error   (22696): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/Error   (22696): 	at android.os.Looper.loop(Looper.java:224)
E/Error   (22696): 	at android.app.ActivityThread.main(ActivityThread.java:7551)
E/Error   (22696): 	at java.lang.reflect.Method.invoke(Native Method)
E/Error   (22696): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/Error   (22696): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
D/AppUtil (22696): -> getAvailablePortNumber -> portNumber 8080 available
**### E/FolioActivity(22696): -> Failed to initialize book**
E/FolioActivity(22696): kotlin.KotlinNullPointerException
E/FolioActivity(22696): 	at com.folioreader.ui.activity.FolioActivity.initBook(FolioActivity.kt:534)
E/FolioActivity(22696): 	at com.folioreader.ui.activity.FolioActivity.setupBook(FolioActivity.kt:487)
E/FolioActivity(22696): 	at com.folioreader.ui.activity.FolioActivity.onCreate(FolioActivity.kt:301)
E/FolioActivity(22696): 	at android.app.Activity.performCreate(Activity.java:7893)
E/FolioActivity(22696): 	at android.app.Activity.performCreate(Activity.java:7880)
E/FolioActivity(22696): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
E/FolioActivity(22696): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3310)
E/FolioActivity(22696): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3484)
E/FolioActivity(22696): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
E/FolioActivity(22696): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/FolioActivity(22696): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/FolioActivity(22696): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2068)
E/FolioActivity(22696): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/FolioActivity(22696): 	at android.os.Looper.loop(Looper.java:224)
E/FolioActivity(22696): 	at android.app.ActivityThread.main(ActivityThread.java:7551)
E/FolioActivity(22696): 	at java.lang.reflect.Method.invoke(Native Method)
E/FolioActivity(22696): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/FolioActivity(22696): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
V/FolioActivity(22696): -> onPostCreate
D/OneSignal(22696): onActivityResumed: com.folioreader.ui.activity.FolioActivity@d581645
D/OneSignal(22696): curActivity is NOW: com.folioreader.ui.activity.FolioActivity:com.folioreader.ui.activity.FolioActivity@d581645
V/FolioActivity(22696): -> onResume
V/PhoneWindow(22696): DecorView setVisiblity: visibility = 4, Parent = null, this = DecorView@e09ed20[]
D/ViewRootImpl[FolioActivity](22696): hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
V/PhoneWindow(22696): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@6cc4f7f, this = DecorView@e09ed20[FolioActivity]
V/FolioAppBarLayout(22696): -> onApplyWindowInsets
E/GraphicExt(22696): GraphicExtModuleLoader::CreateGraphicExtInstance false
D/Surface (22696): Surface::connect(this=0x771ce74000,api=1)
D/mali_winsys(22696): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/Surface (22696): Surface::setBufferCount(this=0x771ce74000,bufferCount=3)
D/Surface (22696): Surface::allocateBuffers(this=0x771ce74000)
D/ForceDarkHelper(22696): updateByCheckExcludeList: pkg: com.muslumanca activity: com.folioreader.ui.activity.FolioActivity@d581645
D/ForceDarkHelper(22696): updateByCheckExcludeList: pkg: com.muslumanca activity: com.folioreader.ui.activity.FolioActivity@d581645
E/FOLIOREADER(22696): Couldn't resolve menu item onClick handler goBackButtonClicked in class com.folioreader.ui.activity.FolioActivity
V/FolioActivity(22696): -> onSystemUiVisibilityChange -> visibility = 0
V/FolioActivity(22696): -> distractionFreeMode = false
D/Surface (22696): Surface::disconnect(this=0x771ca4a000,api=1)
D/ViewRootImpl(22696): setSurfaceViewCreated, created:false
D/Surface (22696): Surface::disconnect(this=0x771ca4a000,api=-1)
D/Surface (22696): Surface::disconnect(this=0x771c992000,api=1)
D/OneSignal(22696): onActivityStopped: com.muslumanca.MainActivity@60446a8
D/OneSignal(22696): curActivity is NOW: com.folioreader.ui.activity.FolioActivity:com.folioreader.ui.activity.FolioActivity@d581645
V/PhoneWindow(22696): DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@622d73f, this = DecorView@425080c[MainActivity]

@JideGuru  this is my registration diary

**Comment by Aksoyhlc** [comment]
@JideGuru Can you please answer?
