### ISSUE TITLE
Compile issue on Android version

### ISSUE THREAD

**Issue by adrian007n** [JideGuru/epub_viewer#9]
I've created a new project and just added "epub_viewer: ^0.1.3" to pubspec.yaml
And run "pub get"

After that, when I try to run from android simulator, it failed to build.
Here is the issues

==========================
/Users/superflutter/Documents/TestProjects/flutter_epub_test/android/app/src/debug/AndroidManifest.xml Error:
	uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [:epub_viewer] /Users/superflutter/Documents/TestProjects/flutter_epub_test/build/epub_viewer/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="com.jideguru.epub_viewer" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [:epub_viewer] /Users/superflutter/Documents/TestProjects/flutter_epub_test/build/epub_viewer/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 16
  	Suggestion: use a compatible library with a minSdk of at most 16,
  		or increase this project's minSdk version to at least 21,
  		or use tools:overrideLibrary="com.jideguru.epub_viewer" to force usage (may lead to runtime failures)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
Exception: Gradle task assembleDebug failed with exit code 1
============================

**Comment by JideGuru** [comment]
Increase the minSdk in your gradle file to 21 instead of 16.

**Comment by JideGuru** [comment]
<img width="615" alt="Screenshot 2020-09-09 at 12 09 25" src="https://user-images.githubusercontent.com/24323581/92591222-63678900-f295-11ea-9f1d-d2b39792cc1c.png">

```
minSdkVersion 21
```

**Comment by adrian007n** [comment]
Hi @JideGuru 
Thanks for your nice suggestion.
I've tried to update minSdkVersion 21.
But I'm getting other issue...  (should I have change settings.gradle?)
Hope you to help me.

=========================
Launching lib/main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /Users/superflutter/.gradle/caches/transforms-2/files-2.1/bf64364ef82cd999d66db3bd84848d01/folioreader-0.5.4/res/layout/progress_dialog.xml:13: AAPT: error: resource android:attr/android:progressBarStyle not found.
         

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 39s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
✏️  Creating `android/settings_aar.gradle`...
Running Gradle task 'assembleAarRelease'...
✓ `android/settings_aar.gradle` created successfully.
Building plugin epub_viewer...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'epub_viewer'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

Exception: The plugin epub_viewer could not be built due to the issue above.

=======================

**Comment by adrian007n** [comment]
Hi @JideGuru 
I this the problem is gradle version is not matched.
Could you please update your gradle version in https://github.com/JideGuru/epub_viewer/blob/master/android/build.gradle
Now, latest version is 4.0.1

**Comment by adrian007n** [comment]
When I downgrade the version to 3.3.1, it works on android emulator.

**Comment by JideGuru** [comment]
Yes @adrian007n its the gradle
I'll work on that

**Comment by adrian007n** [comment]
Great! thanks!  👍

**Comment by JideGuru** [comment]
@adrian007n I pushed a new version with updated Gradle.
