### ISSUE TITLE
epub_viewer ^0.1.9 is incompatible with shared_preferences >=2.0.0.

### ISSUE THREAD

**Issue by ripesol** [JideGuru/epub_viewer#91]
Issue:
trying to publish my app to iOS for which i had to upgrade shared_preference but pub get shows error:

epub_viewer ^0.1.9 is incompatible with shared_preferences >=2.0.0.
kindly get it resolved
Platform (android, iOS or both) -
Crash / Error - 

Steps to reproduce / Describe in detail -

**Comment by JideGuru** [comment]
Update to the latest version
